# Generated by Django 3.0.3 on 2020-06-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_userprofile_fuu_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fuu_name',
            new_name='full_name',
        ),
    ]
